image:
  repository: bboerst/stratum-work-collector
  # tag:
  pullPolicy: IfNotPresent

poolName: "Best Stratum Pool"

arguments:
  - --url
  - "stratum+tcp://beststratumpool.com:3333"
  - --userpass
  - "username:password"
  - --db-url
  - "mongodb://localhost:27017"
  - --db-name
  - "stratum_db"
  - --db-username
  - "admin"
  - --db-password
  - "password"
  - --log-level
  - "INFO"

service:
  enabled: false
  ## Deprecated, instead simply do not provide a clusterIP value
  omitClusterIP: false
  # clusterIP: ""

  ## List of IP addresses at which the controller services are available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  ## Set external traffic policy to: "Local" to preserve source IP on
  ## providers supporting it
  ## Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
  externalTrafficPolicy: ""

  # Must be either "None" or "ClientIP" if set. Kubernetes will default to "None".
  # Ref: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
  sessionAffinity: ""

  healthCheckNodePort: 0

  ports:
    stratum: 3333

  type: ClusterIP

resources:
  requests:
    memory: 40Mi