version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: mquser
      RABBITMQ_DEFAULT_PASS: mqpassword

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
      - MONGO_INITDB_DATABASE=stratum-logger

  # Template for collector services
  collector-base: &collector-base
    build: ./collector
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      ENABLE_HISTORICAL_DATA: ${ENABLE_HISTORICAL_DATA:-true}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: mquser
      RABBITMQ_PASSWORD: mqpassword
      RABBITMQ_EXCHANGE: mining_notify_exchange
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopassword
      MONGODB_HOSTS: mongodb
      SOCKET_URL: http://localhost:8000

  collector-antpool:
    <<: *collector-base
    # Expose unique port for each collector if --enable-stratum-client
    # ports:
    #   - "3333:3333"
    command: >
      /usr/local/bin/python main.py
      --pool-name "Antpool"
      --url "stratum+tcp://ss.antpool.com:443"
      --userpass "developer.001"
      --rabbitmq-host "rabbitmq"
      --rabbitmq-username "mquser"
      --rabbitmq-password "mqpassword"
      --db-url "mongodb"
      --db-name "stratum-logger"
      --db-username "mongouser"
      --db-password "mongopassword"
      --log-level "DEBUG"

  collector-f2pool:
    <<: *collector-base
    # Expose unique port for each collector if --enable-stratum-client
    # ports:
    #   - "3333:3333"
    command: >
      /usr/local/bin/python main.py
      --pool-name "F2Pool"
      --url "stratum+tcp://btc-eu.f2pool.com:3333"
      --userpass "developer1.001:1234567890"
      --rabbitmq-host "rabbitmq"
      --rabbitmq-username "mquser"
      --rabbitmq-password "mqpassword"
      --db-url "mongodb"
      --db-name "stratum-logger"
      --db-username "mongouser"
      --db-password "mongopassword"
      --log-level "DEBUG"

  collector-poolin:
    <<: *collector-base
    # Expose unique port for each collector if --enable-stratum-client
    # ports:
    #   - "3333:3333"
    command: >
      /usr/local/bin/python main.py
      --pool-name "Poolin"
      --url "stratum+tcp://btc.ss.poolin.me:443"
      --userpass "developer1.001:123"
      --rabbitmq-host "rabbitmq"
      --rabbitmq-username "mquser"
      --rabbitmq-password "mqpassword"
      --db-url "mongodb"
      --db-name "stratum-logger"
      --db-username "mongouser"
      --db-password "mongopassword"
      --log-level "DEBUG"

  collector-secpool:
    <<: *collector-base
    # Expose unique port for each collector if --enable-stratum-client
    # ports:
    #   - "3333:3333"
    command: >
      /usr/local/bin/python main.py
      --pool-name "SecPool"
      --url "stratum+tcp://btc.secpool.com:3333"
      --userpass "developer1.001:x"
      --rabbitmq-host "rabbitmq"
      --rabbitmq-username "mquser"
      --rabbitmq-password "mqpassword"
      --db-url "mongodb"
      --db-name "stratum-logger"
      --db-username "mongouser"
      --db-password "mongopassword"
      --log-level "DEBUG"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-development}
    ports:
      - "3000:3000"
    environment:
      ENABLE_HISTORICAL_DATA: ${ENABLE_HISTORICAL_DATA:-true}
      CORS_ORIGINS: "http://localhost:3000"
      ENVIRONMENT: ${ENVIRONMENT:-development}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: mquser
      RABBITMQ_PASSWORD: mqpassword
      RABBITMQ_EXCHANGE: mining_notify_exchange
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopassword
      MONGODB_HOSTS: mongodb
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
      - mongodb
      - backend

  backend:
    build: ./backend
    # command: >
    #   python main.py
    #   --reindex-blocks
    # Comment out the host network mode to use the default bridge network
    # network_mode: host
    environment:
      ENABLE_HISTORICAL_DATA: ${ENABLE_HISTORICAL_DATA:-true}
      BITCOIN_RPC_USER: "rpc_user"
      BITCOIN_RPC_PASSWORD: "rpc_password"
      BITCOIN_RPC_HOST: "host.docker.internal"
      BITCOIN_RPC_PORT: "8332"
      BITCOIN_ZMQ_BLOCK: "tcp://host.docker.internal:28332"
      MONGODB_URL: "mongodb://mongodb:27017"
      MONGODB_DB: "stratum-logger"
      MONGODB_USERNAME: "mongouser"
      MONGODB_PASSWORD: "mongopassword"
      MIN_BLOCK_HEIGHT: "863998"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: "mquser"
      RABBITMQ_PASSWORD: "mqpassword"
      RABBITMQ_EXCHANGE: blocks
      PORT: ${BACKEND_PORT:-8001}
    ports:
      - "${BACKEND_PORT:-8001}:${BACKEND_PORT:-8001}"
    expose:
      - "${BACKEND_PORT:-8001}"
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongo-data:
