version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: mquser
      RABBITMQ_DEFAULT_PASS: mqpassword

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
      - MONGO_INITDB_DATABASE=stratum-logger

  # Template for collector services
  collector-base: &collector-base
    build: ./collector
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: mquser
      RABBITMQ_PASSWORD: mqpassword
      RABBITMQ_EXCHANGE: mining_notify_exchange
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopassword
      MONGODB_HOSTS: mongodb
      SOCKET_URL: http://localhost:8000

  collector-antpool:
    <<: *collector-base
    command: >
      /usr/local/bin/python main.py
      --pool-name "Antpool"
      --url "stratum+tcp://ss.antpool.com:443"
      --userpass "developer.001"
      --rabbitmq-host "rabbitmq"
      --rabbitmq-username "mquser"
      --rabbitmq-password "mqpassword"
      --db-url "mongodb"
      --db-name "stratum-logger"
      --db-username "mongouser"
      --db-password "mongopassword"
      --log-level "DEBUG"

  collector-f2pool:
    <<: *collector-base
    command: >
      /usr/local/bin/python main.py
      --pool-name "F2Pool"
      --url "stratum+tcp://btc-eu.f2pool.com:3333"
      --userpass "developer1.001:1234567890"
      --rabbitmq-host "rabbitmq"
      --rabbitmq-username "mquser"
      --rabbitmq-password "mqpassword"
      --db-url "mongodb"
      --db-name "stratum-logger"
      --db-username "mongouser"
      --db-password "mongopassword"
      --log-level "DEBUG"

  collector-poolin:
    <<: *collector-base
    command: >
      /usr/local/bin/python main.py
      --pool-name "Poolin"
      --url "stratum+tcp://btc.ss.poolin.me:443"
      --userpass "developer1.001:123"
      --rabbitmq-host "rabbitmq"
      --rabbitmq-username "mquser"
      --rabbitmq-password "mqpassword"
      --db-url "mongodb"
      --db-name "stratum-logger"
      --db-username "mongouser"
      --db-password "mongopassword"
      --log-level "DEBUG"

  collector-secpool:
    <<: *collector-base
    command: >
      /usr/local/bin/python main.py
      --pool-name "SecPool"
      --url "stratum+tcp://btc.secpool.com:3333"
      --userpass "developer1.001:x"
      --rabbitmq-host "rabbitmq"
      --rabbitmq-username "mquser"
      --rabbitmq-password "mqpassword"
      --db-url "mongodb"
      --db-name "stratum-logger"
      --db-username "mongouser"
      --db-password "mongopassword"
      --log-level "DEBUG"

  webapp:
    build: ./webapp
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: mquser
      RABBITMQ_PASSWORD: mqpassword
      RABBITMQ_EXCHANGE: mining_notify_exchange
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopassword
      MONGODB_HOSTS: mongodb
      SOCKET_URL: http://localhost:8000
    command:
      - /bin/bash
      - '-c'
      - |
        cat <<EOF > /app/gunicorn.conf.py
        import gunicorn
        bind = "0.0.0.0:8000"
        workers = 1
        worker_class = "eventlet"
        forwarded_allow_ips = "*"
        keepalive = 65
        timeout = 300
        proc_name = "stratum-work"
        loglevel = "info"
        accesslog = "-"
        errorlog = "-"
        gunicorn.SERVER = "undisclosed"
        EOF
        cat /app/gunicorn.conf.py
        gunicorn -c /app/gunicorn.conf.py main:app

volumes:
  mongo-data: