releases:
  {{- range .Values.pools }}
  - name: stratum-work-collector-{{ .poolName | lower | replace " " "-" | replace "." "-"}}
    namespace: stratum-work
    chart: ./stratum-work-collector
    values:
      - image:
          repository: bboerst/stratum-work-collector
          tag: 1
          pullPolicy: IfNotPresent
        poolName: "{{ .poolName }}"
        arguments:
          - --pool-name
          - {{ .poolName }}
        {{- range .arguments }}
          - {{ . }}
        {{- end }}
  {{- end }}