{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "stratum-work-webapp.fullname" . }}
  namespace: {{ template "stratum-work-webapp.namespace" . }}
  labels:
    {{- include "stratum-work-webapp.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "stratum-work-webapp.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.cpuUtilization }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.scaleDownStabilizationSeconds }}
{{- end }}
