
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
    app: {{ template "stratum-work-webapp.fullname" . }}
    chart: {{ template "stratum-work-webapp.chart" . }}
    component: "{{ .Values.name }}"
    heritage: {{ .Release.Service }}
  name: {{ template "stratum-work-webapp.fullname" . }}
spec:
{{- if not .Values.service.omitClusterIP }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ if eq "-" . }}""{{ else }}{{ . | quote }}{{ end }}
  {{- end }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
{{- if .Values.service.sessionAffinity }}
  sessionAffinity: "{{ .Values.service.sessionAffinity }}"
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.service.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.service.healthCheckNodePort }}
{{- end }}
  ports:
    - name: "nextjs"
      port: {{ .Values.service.ports.nextjs }}
      protocol: TCP
      targetPort: "nextjs"
  selector:
    app: {{ template "stratum-work-webapp.fullname" . }}
  type: "{{ .Values.service.type }}"
{{- end }}
