{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "stratum-work-webapp.fullname" . }}
  namespace: {{ template "stratum-work-webapp.namespace" . }}
  labels:
    {{- include "stratum-work-webapp.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "stratum-work-webapp.fullname" . }}
  endpoints:
    - port: nextjs
      path: {{ .Values.serviceMonitor.path }}
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
{{- end }}
